### ISSUE TITLE
Start using issues more!!!

### ISSUE THREAD

**Issue by jackymayo** [jackymayo/bbmoba2d#7]
As @Wai-Lau pointed out we clearly don't use issues enough. Since we only have #6 issues so far, it seems like we need to up our issue game. 
Our first issue is to get TYGUY to make an issue.

Other potential future issues/features:

- [ ] Refactor **ugly** code
- [ ] Redesign system into a 10 000 player scalable structure
- [ ] Remove Godot as engine
- [ ] Start using Wiki and write out Wai's biography
- [ ] Use Ruby, the superior Spotify language

**Comment by fredriclam** [comment]
Solved, used Trello :)

**Comment by jackymayo** [comment]
> Solved, used Trello :)

Closed. Wai will review if he deems it not worthy.
